### ISSUE TITLE
shopsPage - error when duplicate entry

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/FatCat_Server#110]
when trying to add shop or product with the same name i get an error page (code page)
need to check input. 
I guess we have this issue on many pages

**Comment by michaeldub** [comment]
![Product.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5981cb63db8151001f93c916/125516c66e82c728ace21e0d46d88695279780bdcda5fd53b652fa912a5265296b51fa2821d7bb7ae81779545d0c4eac415b0c4da8f1da2fafa42062c80d55b98e30063e937f03a6aa8316b500bf218b498db2bf8a45c5ec3837aa.png)

dont have the this issue with product

will fix the issue with shop store method

branch 110

**Comment by SheyDenis** [comment]
Related #125
