### ISSUE TITLE
Allow user to see current weight in FoodBox

### ISSUE THREAD

**Issue by SheyDenis** [FatCatProject/FatCat_Server#12]

**Comment by SheyDenis** [comment]
Related commit: f7f7a202cb0cede00f823d5200617f685c98ecc6

**Comment by Shabnata** [comment]
add grams on display amount

**Comment by SheyDenis** [comment]
- ~Home page: OK~
- ~Food Products: OK~
- Food boxes: Not OK
- Manage cats: Not OK
- Cat page: Not OK
- CatFields: Not OK
- Vet logs: Not OK (Price USD)
- Shopping page: Not OK (Price USD)
- Shops page: Not OK (Price USD and weight)

**Comment by Shabnata** [comment]
fixed
