### ISSUE TITLE
Two rows of foodboxes - edit div issue

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/FatCat_Server#150]

**Comment by SheyDenis** [comment]
![Screenshot at 2017-11-25 17-41-33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e8dfb0fbe57d001a6a5126/125516c66e82c728ace21e0d46db978826878dba87e6ab03a549b0c67917703e7855ee7925c5b27ff2162a4c5c5c5cb053181d1ba6acda6fb4bc2e75830f0aefd96f5871943813ffb8821fbc52b374831c81bfae965e82b96371b8d6d6056b5c17129bfe553fa19c4ac95ef44ce74d52ad143571ab.png)

**Comment by Shabnata** [comment]
1 - I dont have this issue
2 - we will not present more than 3 boxes, so is it really an issue?
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58fc829d563295002036c784/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1704576217156f47e72d0b12bef122b520c561aa4125c5656e0ebcb7af8e2632dd3165eafc3674d75c13710a9b98319bc07bb22894d82b5aec7.png)

**Comment by SheyDenis** [comment]
Nope.
Looks fixed to me.
