### ISSUE TITLE
Home page - Grams left

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/FatCat_Server#151]
need to round the number to xx.xx
Also show 0 if negative number shows

**Comment by SheyDenis** [comment]
![Screenshot at 2017-11-25 18-19-24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e8dfb0fbe57d001a6a5126/125516c66e82c728ace21e0d46db978826878dba87e6ab03a549b0c67917703e7855ee7925c5b270f213224c5d5b5cb053181d1ba6acda6fb4bc2e75830f0aefd96f5871943813ffb8821fbc52b374831c81bfae965e82b96371b8d6d6056b5c17129bfe543fa19c4ac95ef44ce44d5ca3113271ab.png)
![Screenshot at 2017-11-25 18-24-09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e8dfb0fbe57d001a6a5126/125516c66e82c728ace21e0d46db978826878dba87e6ab03a549b0c67917703e7855ee7925c5b270f2102f4c5f565cb053181d1ba6acda6fb4bc2e75830f0aefd96f5871943813ffb8821fbc52b374831c81bfae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ac95ef44ce44d5ca3113471ab.png)

**Comment by SheyDenis** [comment]
Foods page

**Comment by Shabnata** [comment]
done
