### ISSUE TITLE
add captcha on register

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/FatCat_Server#17]

**Comment by SheyDenis** [comment]
-- Edited --
![Screenshot at 2017-11-25 18-39-40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e8dfb0fbe57d001a6a5126/125516c66e82c728ace21e0d46db978826878dba87e6ab03a549b0c67917703e7855ee7925c5b270f211224c5b5f5cb053181d1ba6acda6fb4bc2e75830f0aefd96f5871943813ffb8821fbc52b374831c81bfae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4ac95ef443e14955a1163771ab.png)

Also it focuses on the name field and not the email field.
