### ISSUE TITLE
forgot password (low priority)

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/FatCat_Server#43]
forgot pass page exists, need to make functionality

**Comment by SheyDenis** [comment]
Very, very <b>VERY</b> `for($i = 0; $i < 100; $i++){ echo "very ";}` low priority.

**Comment by michaeldub** [comment]
had a good solution -> worked fine -> stopped working -> one hour later -> fuck it -> made stupid adjusment -> everything seems to work
